### PR TITLE
Feat/deploy

### PR DESCRIPTION
**Pull request by frederfred**
How it works:

1. Deletes branch `production` if it exists.
2. Creates a branch called `production` from the current branch you are in.
3. Runs build command `npm run build`.
4. Force add the folder `dist` to git (`dist` gets added even though it is in `.gitignore`).
5. Make an automated commit message.
6. Force push the local branch `production` to `<remote>:<branch>` specified.
7. Checks out the branch you was currently in.

### CODE REVIEW

**Comment by lexi** [comment]
Cool!

Maybe be a bit more detailed in the README? So an old chap like me can manage it as well :) Also might be useful to have "How it works" in the README as well?

**Comment by frederfred** [comment]
@lexi I added some more info in readme now. Enough you think?

**Comment by lexi** [comment]
:ok_hand:

**Comment by arvida** [comment]
:beers:

**Comment by lexi** [comment]
@lakrisgubben 

This should be done from our perspective. 

Can you setup so that the `production` branch is automatically deployed to WP Engine and verify that this actually works for you? :smirk:

**Comment by lexi** [comment]
@lakrisgubben Conferred with @frederfred, we’ll add another step between 6 and 7 that deploys to WP Engine. What do you usually call that origin? `production` or `wpengine`?

**Comment by lakrisgubben** [comment]
I was thinking that it could be nice to maybe just send in a flag with the deploy command, something like 

`npm run deploy --production`

and then the script would push to production master. This way it'll be easy to push to staging as well as production...

**Comment by frederfred** [comment]
@lakrisgubben sounds good. Perhaps we should have two arguments: remote and branch. Then the command would be something like

`npm run deploy production master`

Then we don't need to care about everything having the same naming of the remotes

**Comment by lakrisgubben** [comment]
:+1:

**Comment by lexi** [comment]
:+1: :+1:

**Comment by frederfred** [comment]
Said and done! Now you can deploy like this:
`npm run deploy production master`, `npm run deploy wpengine production` or whatever the name of the remote and remote branch is.

**Comment by lexi** [comment]
Weow!

**Comment by lakrisgubben** [comment]
works like a charm!

**Comment by lexi** [comment]
Nice! @frederfred Great work!

**Pull request merged**
